// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-hotels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/data.ts
var catalog = [
  { id: "1", name: "The Grand Azure Resort & Spa", location: "Santorini, Greece", category: "Luxury Resort", starRating: 5, description: "Caldera-cliff suites with private plunge pools and panoramic Aegean views.", priceFromUsd: 349, rating: 4.9, reviews: 2847, amenities: ["Pool", "Spa", "Restaurant", "Bar", "Gym", "Concierge"] },
  { id: "2", name: "Ch\xE2teau Lumi\xE8re Palace", location: "Paris, France", category: "City Hotel", starRating: 5, description: "19th-century palace hotel steps from the Champs-\xC9lys\xE9es.", priceFromUsd: 425, rating: 4.8, reviews: 3421, amenities: ["Spa", "Restaurant", "Bar", "Gym", "Valet", "Concierge"] },
  { id: "3", name: "Palm Oasis Beach Resort", location: "Maldives", category: "Beach Resort", starRating: 5, description: "Overwater bungalows with direct lagoon access.", priceFromUsd: 599, rating: 4.9, reviews: 1856, amenities: ["Private Beach", "Diving", "Spa", "Water Sports"] },
  { id: "4", name: "Skyline Metropolitan Hotel", location: "Dubai, UAE", category: "City Hotel", starRating: 5, description: "Rooftop infinity pool above the Dubai skyline.", priceFromUsd: 289, rating: 4.7, reviews: 4102, amenities: ["Rooftop Pool", "Spa", "Restaurant", "Gym"] },
  { id: "5", name: "Alpine Serenity Lodge", location: "Zermatt, Switzerland", category: "Mountain Lodge", starRating: 4, description: "Ski-in/ski-out lodge beneath the Matterhorn.", priceFromUsd: 375, rating: 4.8, reviews: 1543, amenities: ["Ski Storage", "Spa", "Sauna", "Heated Pool"] },
  { id: "6", name: "The Royal Majestic", location: "London, UK", category: "Boutique Hotel", starRating: 5, description: "Elegant Mayfair boutique with afternoon tea and butler service.", priceFromUsd: 460, rating: 4.8, reviews: 2210, amenities: ["Restaurant", "Bar", "Spa", "Concierge"] },
  { id: "7", name: "Kyoto Garden Ryokan", location: "Kyoto, Japan", category: "Ryokan", starRating: 5, description: "Traditional tatami suites with private onsen and kaiseki dining.", priceFromUsd: 410, rating: 4.9, reviews: 987, amenities: ["Onsen", "Restaurant", "Garden", "Tea Ceremony"] },
  { id: "8", name: "Copacabana Sun Tower", location: "Rio de Janeiro, Brazil", category: "Beach Resort", starRating: 4, description: "Beachfront tower overlooking Copacabana with samba nightlife.", priceFromUsd: 220, rating: 4.6, reviews: 1780, amenities: ["Pool", "Beach", "Bar", "Gym"] },
  { id: "9", name: "Aurora Ice Retreat", location: "Reykjav\xEDk, Iceland", category: "Nature Lodge", starRating: 4, description: "Glass-roof cabins for northern-lights viewing.", priceFromUsd: 520, rating: 4.9, reviews: 640, amenities: ["Hot Springs", "Restaurant", "Aurora Tours"] },
  { id: "10", name: "Sahara Mirage Camp", location: "Merzouga, Morocco", category: "Desert Camp", starRating: 4, description: "Luxury Berber tents deep in the Erg Chebbi dunes.", priceFromUsd: 310, rating: 4.8, reviews: 512, amenities: ["Camel Trek", "Stargazing", "Restaurant"] },
  { id: "11", name: "Amazon Canopy Eco-Lodge", location: "Manaus, Brazil", category: "Eco Lodge", starRating: 4, description: "Treetop cabins with guided rainforest expeditions.", priceFromUsd: 275, rating: 4.7, reviews: 430, amenities: ["Guided Tours", "Restaurant", "Kayaks"] },
  { id: "12", name: "Bora Bora Pearl Lagoon", location: "Bora Bora, French Polynesia", category: "Beach Resort", starRating: 5, description: "Iconic overwater villas above a turquoise lagoon.", priceFromUsd: 890, rating: 4.9, reviews: 1120, amenities: ["Overwater Villa", "Spa", "Diving", "Bar"] },
  { id: "13", name: "Tuscan Vineyard Estate", location: "Tuscany, Italy", category: "Countryside Villa", starRating: 5, description: "Restored 16th-century villa amid working vineyards.", priceFromUsd: 395, rating: 4.9, reviews: 720, amenities: ["Wine Tasting", "Pool", "Restaurant"] },
  { id: "14", name: "Manhattan Skyline Tower", location: "New York, USA", category: "City Hotel", starRating: 5, description: "Midtown tower with Central Park views and rooftop bar.", priceFromUsd: 510, rating: 4.7, reviews: 3300, amenities: ["Gym", "Bar", "Restaurant", "Business Center"] },
  { id: "15", name: "Patagonia Wilderness Retreat", location: "Torres del Paine, Chile", category: "Nature Lodge", starRating: 4, description: "All-inclusive lodge with guided treks in Torres del Paine.", priceFromUsd: 640, rating: 4.9, reviews: 380, amenities: ["Guided Hikes", "Spa", "Restaurant"] },
  { id: "16", name: "Marrakech Riad Mirage", location: "Marrakech, Morocco", category: "Riad", starRating: 5, description: "Historic riad in the medina with rooftop hammam.", priceFromUsd: 260, rating: 4.8, reviews: 890, amenities: ["Hammam", "Pool", "Restaurant", "Rooftop"] }
];
var destinations = [
  { name: "Santorini, Greece", hotels: 1 },
  { name: "Paris, France", hotels: 1 },
  { name: "Maldives", hotels: 1 },
  { name: "Dubai, UAE", hotels: 1 },
  { name: "Zermatt, Switzerland", hotels: 1 },
  { name: "London, UK", hotels: 1 },
  { name: "Kyoto, Japan", hotels: 1 },
  { name: "Rio de Janeiro, Brazil", hotels: 1 },
  { name: "Reykjav\xEDk, Iceland", hotels: 1 },
  { name: "Merzouga, Morocco", hotels: 1 },
  { name: "Manaus, Brazil", hotels: 1 },
  { name: "Bora Bora, French Polynesia", hotels: 1 },
  { name: "Tuscany, Italy", hotels: 1 },
  { name: "New York, USA", hotels: 1 },
  { name: "Torres del Paine, Chile", hotels: 1 },
  { name: "Marrakech, Morocco", hotels: 1 }
];

// src/lib/mcp/tools/search-hotels.ts
var search_hotels_default = defineTool({
  name: "search_hotels",
  title: "Search hotels",
  description: "Search the StayVista hotel catalog by destination, category, star rating, and price range.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text match against name, location, or description."),
    location: z.string().trim().optional().describe("Filter by destination substring, e.g. 'Paris' or 'Morocco'."),
    category: z.string().trim().optional().describe("Filter by category, e.g. 'Beach Resort', 'City Hotel'."),
    minStarRating: z.number().int().min(1).max(5).optional(),
    maxPriceUsd: z.number().positive().optional().describe("Maximum nightly starting price in USD."),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, location, category, minStarRating, maxPriceUsd, limit }) => {
    const q = query?.toLowerCase();
    const results = catalog.filter((h) => {
      if (q && !`${h.name} ${h.location} ${h.description}`.toLowerCase().includes(q)) return false;
      if (location && !h.location.toLowerCase().includes(location.toLowerCase())) return false;
      if (category && !h.category.toLowerCase().includes(category.toLowerCase())) return false;
      if (minStarRating && h.starRating < minStarRating) return false;
      if (maxPriceUsd && h.priceFromUsd > maxPriceUsd) return false;
      return true;
    }).slice(0, limit);
    return {
      content: [{ type: "text", text: `Found ${results.length} hotel(s).` }],
      structuredContent: { count: results.length, hotels: results }
    };
  }
});

// src/lib/mcp/tools/get-hotel.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_hotel_default = defineTool2({
  name: "get_hotel",
  title: "Get hotel details",
  description: "Retrieve full public details for a single hotel by its id.",
  inputSchema: {
    id: z2.string().min(1).describe("Hotel id from search_hotels (e.g. '1', '12').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const hotel = catalog.find((h) => h.id === id);
    if (!hotel) {
      return { content: [{ type: "text", text: `No hotel found with id '${id}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `${hotel.name} \u2014 ${hotel.location} (${hotel.starRating}\u2605)` }],
      structuredContent: { hotel }
    };
  }
});

// src/lib/mcp/tools/list-destinations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_destinations_default = defineTool3({
  name: "list_destinations",
  title: "List destinations",
  description: "List every destination StayVista features, with how many properties each has.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: `${destinations.length} destinations available.` }],
    structuredContent: { count: destinations.length, destinations }
  })
});

// src/lib/mcp/tools/recommend-hotels.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var recommend_hotels_default = defineTool4({
  name: "recommend_hotels",
  title: "Recommend hotels",
  description: "Recommend top-rated StayVista hotels for a travel style (beach, city, mountain, nature, cultural, luxury).",
  inputSchema: {
    style: z3.enum(["beach", "city", "mountain", "nature", "cultural", "luxury"]).describe("Preferred travel style."),
    limit: z3.number().int().min(1).max(10).default(5)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ style, limit }) => {
    const bucket = {
      beach: (c) => /Beach|Overwater|Lagoon/i.test(c.category + c.description),
      city: (c) => /City Hotel|Boutique/i.test(c.category),
      mountain: (c) => /Mountain|Ski|Alpine|Patagonia/i.test(c.category + c.description),
      nature: (c) => /Nature|Eco|Desert|Aurora|Amazon|Patagonia/i.test(c.category + c.description),
      cultural: (c) => /Ryokan|Riad|Château|Kyoto|Marrakech|Tuscan/i.test(c.category + c.name),
      luxury: (c) => c.starRating === 5
    };
    const picks = catalog.filter(bucket[style]).sort((a, b) => b.rating - a.rating).slice(0, limit);
    return {
      content: [{ type: "text", text: `Top ${picks.length} ${style} pick(s).` }],
      structuredContent: { style, hotels: picks }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "stayvista-mcp",
  title: "StayVista MCP",
  version: "0.1.0",
  instructions: "Public catalog tools for StayVista, a luxury hotel booking platform. Use `search_hotels` to filter by destination, category, star rating, or price. Use `get_hotel` for full details of a single property. Use `list_destinations` to see all featured destinations, and `recommend_hotels` to suggest properties for a travel style (beach, city, mountain, nature, cultural, luxury). All data is public catalog information \u2014 no bookings or user data are exposed.",
  tools: [search_hotels_default, get_hotel_default, list_destinations_default, recommend_hotels_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
